# Generated by Django 6.0 on 2025-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mody_stare', models.FileField(upload_to='mody_stare')),
                ('mody_nowe', models.FileField(upload_to='mody_nowe')),
                ('wynik', models.FileField(upload_to='wynik')),
            ],
        ),
    ]
