# Generated by Django 6.0 on 2025-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mody',
            name='mody_name',
            field=models.CharField(default='MODS', max_length=100),
        ),
    ]
