# Generated by Django 6.0 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_mody_mody_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mody',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mody',
            name='mody_name',
        ),
        migrations.RemoveField(
            model_name='mody',
            name='wynik',
        ),
        migrations.AddField(
            model_name='mody',
            name='mody_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mody',
            name='mody_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
